name: GitHub to Snowflake

on:
  push:
    paths:
      - '*.csv'

jobs:
  load-to-snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Cloner le repo
        uses: actions/checkout@v3

      - name: 🐍 Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Installer dépendances
        run: pip install snowflake-connector-python

      - name: 🚀 Lancer le chargement dans Snowflake
        run: python .github/scripts/load_to_snowflake.py
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_STAGE: ${{ secrets.SNOWFLAKE_STAGE }}
